In [51]:
#notebook of all code experiments
import pandas as pd 
import numpy as np

In [52]:
pred=pd.read_csv("YOLOv5_config/utils/predictions.csv")
sample=pd.read_csv("/Volumes/T7 Shield/Smudge/Datasets/Wheat_Head_detection/submission.csv")

In [53]:
pred.shape

(2818, 3)

In [54]:
pred_names=list(pred['image_name'])
pred_boxes=list(pred['BoxString'])
sample_names=list(sample['image_name'])

In [55]:
len(sample_names)
len(pred_names)

2818

In [56]:
for i in sample_names:
    if i not in pred_names:
        pred_names.append(i)
        pred_boxes.append('no_box')

In [57]:
pred_new=pd.DataFrame({
    'image_name':pred_names,
    'BoxString':pred_boxes
})

pred_new.to_csv("pred_edited.csv",)

In [65]:
pred_act=pd.read_csv("pred_edited.csv")

In [66]:
pred_act

,image_name,BoxString
0,9fd057f42b34f760218aa585ceb27f69040f31f8fecae1...,50.0000256 611.0000128 24.9999872 518.9999616;...
1,f68141b08bbb31b4bbd68cfed3fff2c412e0e43273652a...,1086.0004864 712.9997312 1024.0004608 653.9997...
2,158d6fa793fc03fc26495bba701b368818755ec05cd7e4...,1258.000384 1102.0001280000001 1024.0 906.9998...
3,7a9a1b46213d641c76b99db53cb59d28feadb1c2eff985...,644.999168 366.99970559999997 526.999552 284.9...
4,042613ea0042e762b61d82e65cc077151e2a6e15f8ccb5...,924.9997824 344.00030719999995 893.9998208 324...
...,...,...
2851,ab1b2e30b5acf9162c42e267aae2c6129f0aeb867877aa...,no_box
2852,12797d0bc164d1fe8785ef2a7c0ba872ab17b684bdf18d...,no_box
2853,9b92add99dcaf2aea1dd9b8c1371397f12907ad1dad256...,no_box
2854,ddea3cdda8a7736aafeafce0998f3d75a1004654bbc883...,no_box
2855,bb73dbfd5a20df633eb3f7aca87d01cb9d63ac3263c01e...,no_box

In [68]:
sample

                                             image_name  domain PredString
0     c087c8b89904edee56997a25d64f4cd1b7c9441e64889a...      18     no_box
1     b11a617a64ca6120021e70b107933ddb70bf052395759d...      18     no_box
2     4fd7a4dc7dc60b5daedc7d57fdf8000ef3cab267654b56...      18     no_box
3     3f60fada17caf269a8d70798eb3bb5771f2c10d13c887e...      18     no_box
4     8cdcb28a926c217d0b587fcba2050e283b3175824a5b6e...      18     no_box
...                                                 ...     ...        ...
2844  488ea848ee35b06b561c2aa525c75705aee00d0e3f7dd6...      46     no_box
2845  fdd6a2154713b72644a3f818f4318a48816aa2779aad13...      46     no_box
2846  4444cfa1f1f96c17c80ee5c918279313bd134fb743b7ba...      46     no_box
2847  dd5a7bbca426d211984d6ea6595b2976ed77652791936a...      46     no_box
2848  bb73dbfd5a20df633eb3f7aca87d01cb9d63ac3263c01e...      46     no_box

[2849 rows x 3 columns]

In [69]:
res=pd.merge(sample,pred_act,on=['image_name'])

In [70]:
res.shape

(2849, 4)

In [71]:
res

,image_name,domain,PredString,BoxString
0,c087c8b89904edee56997a25d64f4cd1b7c9441e64889a...,18,no_box,113.0000384 111.9999488 65.0000384 66.9999616;...
1,b11a617a64ca6120021e70b107933ddb70bf052395759d...,18,no_box,50.0000256 860.0004608 24.9999872 823.00047360...
2,4fd7a4dc7dc60b5daedc7d57fdf8000ef3cab267654b56...,18,no_box,511.9995904 39.99991808 432.9996288 19.9999692...
3,3f60fada17caf269a8d70798eb3bb5771f2c10d13c887e...,18,no_box,506.9999616 640.0003072000001 456.9999872 604....
4,8cdcb28a926c217d0b587fcba2050e283b3175824a5b6e...,18,no_box,197.9999232 1066.9999104 118.9999616 996.99988...
...,...,...,...,...
2844,488ea848ee35b06b561c2aa525c75705aee00d0e3f7dd6...,46,no_box,1064.9995776 218.00058879999997 1023.9995392 1...
2845,fdd6a2154713b72644a3f818f4318a48816aa2779aad13...,46,no_box,740.9995776 800.9998336 666.9996031999999 758....
2846,4444cfa1f1f96c17c80ee5c918279313bd134fb743b7ba...,46,no_box,76.0000512 161.9999232 38.0000256 111.9999488;...
2847,dd5a7bbca426d211984d6ea6595b2976ed77652791936a...,46,no_box,560.000256 51.9999488 504.000256 25.9999744;35...
2848,bb73dbfd5a20df633eb3f7aca87d01cb9d63ac3263c01e...,46,no_box,no_box

In [72]:
res=res.drop(columns=['PredString'],axis=1)

In [73]:
res

,image_name,domain,BoxString
0,c087c8b89904edee56997a25d64f4cd1b7c9441e64889a...,18,113.0000384 111.9999488 65.0000384 66.9999616;...
1,b11a617a64ca6120021e70b107933ddb70bf052395759d...,18,50.0000256 860.0004608 24.9999872 823.00047360...
2,4fd7a4dc7dc60b5daedc7d57fdf8000ef3cab267654b56...,18,511.9995904 39.99991808 432.9996288 19.9999692...
3,3f60fada17caf269a8d70798eb3bb5771f2c10d13c887e...,18,506.9999616 640.0003072000001 456.9999872 604....
4,8cdcb28a926c217d0b587fcba2050e283b3175824a5b6e...,18,197.9999232 1066.9999104 118.9999616 996.99988...
...,...,...,...
2844,488ea848ee35b06b561c2aa525c75705aee00d0e3f7dd6...,46,1064.9995776 218.00058879999997 1023.9995392 1...
2845,fdd6a2154713b72644a3f818f4318a48816aa2779aad13...,46,740.9995776 800.9998336 666.9996031999999 758....
2846,4444cfa1f1f96c17c80ee5c918279313bd134fb743b7ba...,46,76.0000512 161.9999232 38.0000256 111.9999488;...
2847,dd5a7bbca426d211984d6ea6595b2976ed77652791936a...,46,560.000256 51.9999488 504.000256 25.9999744;35...
2848,bb73dbfd5a20df633eb3f7aca87d01cb9d63ac3263c01e...,46,no_box

In [75]:
res=res.rename(columns={'BoxString':'PredString'})

In [78]:
res.to_csv("submission_1.csv")